# application.yml

spring:
  profiles:
    active: dev
  application:
    name: faraday-service

server:
  error:
    whitelabel:
      enabled: false

staffjoy:
  common:
    deploy-env: ${DEPLOY:V2}
  signing-secret: signing_secret
#  signing-secret: ${SIGNING_SECRET}